import mysql.connector

mydb  = mysql.connector.connect(host="localhost",user="root",password="",database="blog")

mycursor = mydb.cursor()

mycursor.execute("CREATE TABLE contact (sno INT AUTO_INCREMENT PRIMARY KEY, name varchar(20), phone_no varchar(12), mess varchar(100), date varchar(12),email varchar(20));")
mycursor.execute("CREATE TABLE posts (sno INT AUTO_INCREMENT PRIMARY KEY, title varchar(50), subtitle varchar(50), content text, slug varchar(100), author varchar(20), date varchar(20), img_url varchar(50));")

mycursor.execute("INSERT into posts (title , subtitle , content , slug , author , date , img_url ) VALUES (\"Go on Safari in Tanzania\",\"Biggest and Baddest national parks\", \"Tanzania is the perfect place to watch the annual wildebeest migration. Watching baby elephants playing with their moms and pops in the muddy Rufiji/Tarangire River is one of the epic lifetime experiences to keep in your memories bright for decades.\",\"Go-on-Safari-in-Tanzania-by-alfred-thomas\",\"Alfred Thomas\",\"20-01-2020\",\"\");")
mycursor.execute("INSERT into posts (title , subtitle , content , slug , author , date , img_url ) VALUES (\"Heli skiing in Girdwood, Alaska\",\"You need courage to do this!!\",\"Now if you have enough skills and bald courage, heli-skiing is one of the life changing experiences! Named as best for “Off-the-beaten-path powder hounds with an aversion to glamour” by Nat Geo, Girdwood has loads of incredible hills and off-pistes where you can be the first one to shake off the powder. Day trips with 16,000-18,000 vertical feet of skiing guaranteed start from $1,275 per person.\",\"Heli-skiing-in-Girdwood,-Alaska-Natlie-chamalo\",\"Natlie chamalo\",\"10-11-2019\",\"\");")
mycursor.execute("INSERT into posts (title , subtitle , content , slug , author , date , img_url ) VALUES (\"Heli skiing in Girdwood, Alaska\",\"You need courage to do this!!\",\"Now if you have enough skills and bald courage, heli-skiing is one of the life changing experiences! Named as best for “Off-the-beaten-path powder hounds with an aversion to glamour” by Nat Geo, Girdwood has loads of incredible hills and off-pistes where you can be the first one to shake off the powder. Day trips with 16,000-18,000 vertical feet of skiing guaranteed start from $1,275 per person.\",\"Heli-skiing-in-Girdwood,-Alaska-Natlie-chamalo\",\"Natlie chamalo\",\"10-10-2019\",\"\");")
mycursor.execute("INSERT into posts (title , subtitle , content , slug , author , date , img_url ) VALUES (\"Go on Safari in Tanzania\",\"Biggest and Baddest national parks\", \"Tanzania is the perfect place to watch the annual wildebeest migration. Watching baby elephants playing with their moms and pops in the muddy Rufiji/Tarangire River is one of the epic lifetime experiences to keep in your memories bright for decades.\",\"Go-on-Safari-in-Tanzania-by-alfred-thomas\",\"Alfred Thomas\",\"05-07-2019\",\"\");")
mycursor.execute("INSERT into posts (title , subtitle , content , slug , author , date , img_url ) VALUES (\"Go on Safari in Tanzania\",\"Biggest and Baddest national parks\", \"Tanzania is the perfect place to watch the annual wildebeest migration. Watching baby elephants playing with their moms and pops in the muddy Rufiji/Tarangire River is one of the epic lifetime experiences to keep in your memories bright for decades.\",\"Go-on-Safari-in-Tanzania-by-alfred-thomas\",\"Alfred Thomas\",\"20-10-2018\",\"\");")

mydb.commit()